# Generated by Django 5.2.1 on 2025-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttask",
            name="pdf_path",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
    ]
